# The basic colors
foreground              #FFFFFF
background              #EEEEEE

background_opacity 0.1

window_padding_width 20

#: black
color0 #1D1F21
color8 #666666

#: red
color1 #CC6666
color9 #D54E53

#: green
color2  #B5BD68
color10 #B9CA4A

#: yellow
color3  #F0C674
color11 #E7C547

#: blue
color4  #81A2BE
color12 #7AA6DA

#: magenta
color5  #B294BB
color13 #C397D8

#: cyan
color6  #8ABEB7
color14 #70C0B1

#: white
color7  #C5C8C6
color15 #EAEAEA


font_family JetBrains Mono
font_size 16
