corner-radius = 10;

rounded-corners-exclude = [
    "override_redirect = true",
]

fading = true
fade-in-step = 0.08;
fade-out-step = 0.08;


#inactive-opacity = 0.85

#focus-exclude = ["x = 0 && y = 0 && override_redirect = true"];

opacity-rule = [
    "85:class_g = 'Code'",
    "88:class_g = 'discord'",
];

blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

backend = "xrender";

mark-wmwin-focused = true;

#detect-rounded-corners = true;
