corner-radius = 5;

rounded-corners-exclude = [
    "override_redirect = true",
]

shadow-radius = 15;
shadow-opacity = 0.5;
shadow-offset-x = -15;
shadow-offset-y = -15;

shadow-exclude = [
  "name = 'Notification'",
  "class_g ?= 'Notify-osd'",
  "_GTK_FRAME_EXTENTS@:c",
  "x = 0 && y = 0 && override_redirect = true",
];

fading = true
fade-in-step = 0.03;
fade-out-step = 0.03;

wintypes:
{
  tooltip = { fade = true; shadow = false; opacity = 1.0; focus = true; };
  dock = { shadow = false; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 1.0; shadow = false; }
  dropdown_menu = { opacity = 1.0; shadow = false;}
};
