[colors]
background = #1E1E2E
background-alt = #302D41
foreground = #F5C2E7
primary = #FAE3BO
secondary = #8ABEB7
alert = #A54242
disabled = #575268

[bar/bar]
width = 100%
height = 30pt
radius = 5

background = ${colors.background}
foreground = ${colors.foreground}

padding-left = 1
padding-right = 1

border-size = 12
border-color = #0000000

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = Fira Code Medium;2

modules-left = xwindow
modules-center = xworkspaces
modules-right = date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

tray-position = left

wm-restack = bspwm

; override-redirect = true

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/date]
type = internal/date
interval = 1

date = %A %e. %H:%M
date-alt = %Y-%m-%d %H:%M:%S

label = %date%
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true
