general {
    gaps_in = 7
    gaps_out = 25

    border_size = 2

    col.active_border = rgb(eceff4) rgb(e5e9f0) 45deg
    col.inactive_border = rgba(2e3440ff)

    allow_tearing = false
}

$cursorTheme = Simp1e-Nord-Light

env = HYPRCURSOR_THEME,$cursorTheme
env = HYPRCURSOR_SIZE,24
env = XCURSOR_THEME,$cursorTheme
env = XCURSOR_SIZE,24

exec-once = gsettings set org.gnome.desktop.interface cursor-theme $cursorTheme
exec-once = hyprctl setcursor $cursorTheme


windowrule {
    name = disable-unfocused-shadow
    match:focus = 0
    no_shadow = yes
}
# windowrule = noshadow, focus:0
decoration {
    rounding = 12

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 0.94

    shadow {
        enabled = true
        range = 20
        render_power = 3
        # color = rgba(00000066)
        color = rgba(eceff433)
    }

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 5
        passes = 2

        vibrancy = 0.1696
    }
}

# https://wiki.hypr.land/Configuring/Variables/#animations
animations {
    enabled = yes, please :)

    # Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
    #        NAME,           X0,   Y0,   X1,   Y1
    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1

    # Default animations, see https://wiki.hypr.land/Configuring/Animations/
    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = global,        1,     10,    default
    animation = border,        1,     5.39,  easeOutQuint
    animation = windows,       1,     4.79,  easeOutQuint
    animation = windowsIn,     1,     4.1,   easeOutQuint, popin 87%
    animation = windowsOut,    1,     1.49,  linear,       popin 87%
    animation = fadeIn,        1,     1.73,  almostLinear
    animation = fadeOut,       1,     1.46,  almostLinear
    animation = fade,          1,     3.03,  quick
    animation = layers,        1,     3.81,  easeOutQuint
    animation = layersIn,      1,     4,     easeOutQuint, fade
    animation = layersOut,     1,     1.5,   linear,       fade
    animation = fadeLayersIn,  1,     1.79,  almostLinear
    animation = fadeLayersOut, 1,     1.39,  almostLinear
    animation = workspaces,    1,     1.94,  almostLinear, fade
    animation = workspacesIn,  1,     1.21,  almostLinear, fade
    animation = workspacesOut, 1,     1.94,  almostLinear, fade
    animation = zoomFactor,    1,     7,     quick
}

misc {
    col.splash = rgb(d8dee9)
    splash_font_family = Rubik
    animate_manual_resizes = true
}

plugin {
    hyprbars {
        bar_height = 24
        hyprbars-button = rgb(bf616a), 12, , hyprctl dispatch killactive
        bar_color = rgba(eceff4ea)
        col.text = rgb(2e3440)
        # bar_color = rgba(2e3440ff)
        # col.text = rgb(eceff4)
        bar_blur = true
        bar_precedence_over_border = true
    }
}
