#! /bin/sh
bspc config window_gap          12
bspc config border_width          1
# make sure to use bspwm-rounded from AUR
bspc config border_radius         15
bspc config normal_border_color	  "#777777"
bspc config active_border_color	  "#999999"
bspc config focused_border_color  "#dddddd"
bspc config presel_feedback_color "#222222"
