#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d TERM WEB CODE DISC EXTRA

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.54
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus    true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a firefox desktop='^2' focus=off
bspc rule -a discord desktop='^4' focus=off
bspc rule -a kitty focus=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
