#! /bin/sh

# CONFIG
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor VGA-0  -d 6 7 8 9
bspc monitor eDP-1  -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config ignore_ewmh_focus    true
bspc config gapless_monocle      false
bspc config borderless_monocle   false

# this is only for nord for now
bspc config border_width          1
# make sure to use bspwm-rounded from AUR
bspc config border_radius         7
bspc config normal_border_color	  "#2E3440"
bspc config active_border_color	  "#4C566A"
bspc config focused_border_color  "#D8DEE9"
bspc config presel_feedback_color "#81A1C1"

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a -o firefox desktop='^2' focus=off
bspc rule -a discord desktop='^6' focus=off
bspc rule -a -o kitty focus=on
bspc rule -a feh state=floating
bspc rule -a school state=floating

if [[ -f ./themerc ]]; then
  ./themerc
fi

bspc config -m VGA-0 top_padding 0

# STARTUP PROGRAMS
polybar -r &
picom &
dunst &
