#! /bin/sh
bspc config window_gap          12
bspc config border_width          1
# make sure to use bspwm-rounded from AUR
bspc config border_radius         7
bspc config normal_border_color	  "#2E3440"
bspc config active_border_color	  "#4C566A"
bspc config focused_border_color  "#D8DEE9"
bspc config presel_feedback_color "#81A1C1"
