font_family      ProggyCleanTTSZ
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        18
foreground #e5e5e5
background #1C1C1C

selection_foreground #000000
selection_background #fffacd


color0 #000000
color8 #000000

#: black

color1 #ff005b
color9 #ff00a0

#: red

color2  #cee318
color10 #ccff00

#: green

color3  #ffe755
color11 #ff9f00

#: yellow

color4  #048ac7
color12 #48c6ff

#: blue

color5  #833c9f
color13 #be67e1

#: magenta

color6  #0abdc9
color14 #63e7f0

#: cyan

color7  #e5e5e5
color15 #f3f3f3

#: white

mark1_foreground black

#: Color for marks of type 1

mark1_background #98d3cb

#: Color for marks of type 1 (light steel blue)

mark2_foreground black

#: Color for marks of type 2

mark2_background #f2dcd3

#: Color for marks of type 1 (beige)

mark3_foreground black

#: Color for marks of type 3

mark3_background #f274bc

#: Color for marks of type 3 (violet)
