#! /bin/sh
bspc config window_gap          12
bspc config border_width          1
# make sure to use bspwm-rounded from AUR
bspc config border_radius         7
bspc config normal_border_color	  "#53605c"
bspc config active_border_color	  "#7a8478"
bspc config focused_border_color  "#d3c6aa"
bspc config presel_feedback_color "#d3c6aa"
