#! /bin/sh
bspc config window_gap          5
bspc config border_width          1
# make sure to use bspwm-rounded from AUR
# bspc config border_radius         10
bspc config normal_border_color	  "#111111"
bspc config active_border_color	  "#111111"
bspc config focused_border_color  "#FFFFFF"
bspc config presel_feedback_color "#999999"
