#! /bin/sh
bspc config window_gap          20
bspc config border_width          2
# make sure to use bspwm-rounded from AUR
bspc config border_radius         0
bspc config normal_border_color	  "#1F1F1F"
bspc config active_border_color	  "#546E7A"
bspc config focused_border_color  "#FFFFFF"
bspc config presel_feedback_color "#546E7A"
